### ISSUE TITLE
time to improve this blog don't you think ?

### ISSUE THREAD

**Issue by bcdbuddy** [bcdbuddy/blog#1]

**Comment by kouna77** [comment]
Yes of course I thought I would do it again with typescript and mongodb what do you think

**Comment by bcdbuddy** [comment]
- [ ] make it with typescript
- [ ] add mongo
- [ ] deploy it on heroku

go for it! you have all my support! 
![](https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif)

**Comment by kouna77** [comment]
Ok thank you
